//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WPSort.ru.boxberry.service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AccountSoapBinding", Namespace="http://service.boxberry.ru")]
    public partial class Account : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RequisitesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ServicesBoxberryOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckAPIOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Account() {
            this.Url = global::WPSort.Properties.Settings.Default.WPSort_ru_boxberry_service_Account;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RequisitesCompletedEventHandler RequisitesCompleted;
        
        /// <remarks/>
        public event ServicesBoxberryCompletedEventHandler ServicesBoxberryCompleted;
        
        /// <remarks/>
        public event ListCategoriesCompletedEventHandler ListCategoriesCompleted;
        
        /// <remarks/>
        public event CheckAPICompletedEventHandler CheckAPICompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.boxberry.ru#Account:Requisites", RequestNamespace="http://service.boxberry.ru", ResponseNamespace="http://service.boxberry.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public Results Requisites(
                    string name, 
                    string inn, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string kpp, 
                    string r_s, 
                    string bank, 
                    string kor_s, 
                    string bik, 
                    string phone, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, 
                    string token, 
                    string City_Recipient, 
                    string Point_Recipient, 
                    string fio, 
                    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")] string Categorie, 
                    string Website, 
                    string PostCode, 
                    string City, 
                    string Street, 
                    string House, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Building, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Housing, 
                    string NameOfHead, 
                    string PositionOfHead, 
                    string FoundationOfHead, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string СontactNumber, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string PromoCode) {
            object[] results = this.Invoke("Requisites", new object[] {
                        name,
                        inn,
                        kpp,
                        r_s,
                        bank,
                        kor_s,
                        bik,
                        phone,
                        email,
                        token,
                        City_Recipient,
                        Point_Recipient,
                        fio,
                        Categorie,
                        Website,
                        PostCode,
                        City,
                        Street,
                        House,
                        Building,
                        Housing,
                        NameOfHead,
                        PositionOfHead,
                        FoundationOfHead,
                        СontactNumber,
                        PromoCode});
            return ((Results)(results[0]));
        }
        
        /// <remarks/>
        public void RequisitesAsync(
                    string name, 
                    string inn, 
                    string kpp, 
                    string r_s, 
                    string bank, 
                    string kor_s, 
                    string bik, 
                    string phone, 
                    string email, 
                    string token, 
                    string City_Recipient, 
                    string Point_Recipient, 
                    string fio, 
                    string Categorie, 
                    string Website, 
                    string PostCode, 
                    string City, 
                    string Street, 
                    string House, 
                    string Building, 
                    string Housing, 
                    string NameOfHead, 
                    string PositionOfHead, 
                    string FoundationOfHead, 
                    string СontactNumber, 
                    string PromoCode) {
            this.RequisitesAsync(name, inn, kpp, r_s, bank, kor_s, bik, phone, email, token, City_Recipient, Point_Recipient, fio, Categorie, Website, PostCode, City, Street, House, Building, Housing, NameOfHead, PositionOfHead, FoundationOfHead, СontactNumber, PromoCode, null);
        }
        
        /// <remarks/>
        public void RequisitesAsync(
                    string name, 
                    string inn, 
                    string kpp, 
                    string r_s, 
                    string bank, 
                    string kor_s, 
                    string bik, 
                    string phone, 
                    string email, 
                    string token, 
                    string City_Recipient, 
                    string Point_Recipient, 
                    string fio, 
                    string Categorie, 
                    string Website, 
                    string PostCode, 
                    string City, 
                    string Street, 
                    string House, 
                    string Building, 
                    string Housing, 
                    string NameOfHead, 
                    string PositionOfHead, 
                    string FoundationOfHead, 
                    string СontactNumber, 
                    string PromoCode, 
                    object userState) {
            if ((this.RequisitesOperationCompleted == null)) {
                this.RequisitesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequisitesOperationCompleted);
            }
            this.InvokeAsync("Requisites", new object[] {
                        name,
                        inn,
                        kpp,
                        r_s,
                        bank,
                        kor_s,
                        bik,
                        phone,
                        email,
                        token,
                        City_Recipient,
                        Point_Recipient,
                        fio,
                        Categorie,
                        Website,
                        PostCode,
                        City,
                        Street,
                        House,
                        Building,
                        Housing,
                        NameOfHead,
                        PositionOfHead,
                        FoundationOfHead,
                        СontactNumber,
                        PromoCode}, this.RequisitesOperationCompleted, userState);
        }
        
        private void OnRequisitesOperationCompleted(object arg) {
            if ((this.RequisitesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequisitesCompleted(this, new RequisitesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.boxberry.ru#Account:ServicesBoxberry", RequestNamespace="http://service.boxberry.ru", ResponseNamespace="http://service.boxberry.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public Results ServicesBoxberry([System.Xml.Serialization.XmlArrayItemAttribute(Namespace="Account", IsNullable=false)] ServicesBoxberry[] ArrayServicesBoxberry, string id) {
            object[] results = this.Invoke("ServicesBoxberry", new object[] {
                        ArrayServicesBoxberry,
                        id});
            return ((Results)(results[0]));
        }
        
        /// <remarks/>
        public void ServicesBoxberryAsync(ServicesBoxberry[] ArrayServicesBoxberry, string id) {
            this.ServicesBoxberryAsync(ArrayServicesBoxberry, id, null);
        }
        
        /// <remarks/>
        public void ServicesBoxberryAsync(ServicesBoxberry[] ArrayServicesBoxberry, string id, object userState) {
            if ((this.ServicesBoxberryOperationCompleted == null)) {
                this.ServicesBoxberryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServicesBoxberryOperationCompleted);
            }
            this.InvokeAsync("ServicesBoxberry", new object[] {
                        ArrayServicesBoxberry,
                        id}, this.ServicesBoxberryOperationCompleted, userState);
        }
        
        private void OnServicesBoxberryOperationCompleted(object arg) {
            if ((this.ServicesBoxberryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ServicesBoxberryCompleted(this, new ServicesBoxberryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.boxberry.ru#Account:ListCategories", RequestNamespace="http://service.boxberry.ru", ResponseNamespace="http://service.boxberry.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("Categories", Namespace="Account", IsNullable=false)]
        public Categorie[] ListCategories() {
            object[] results = this.Invoke("ListCategories", new object[0]);
            return ((Categorie[])(results[0]));
        }
        
        /// <remarks/>
        public void ListCategoriesAsync() {
            this.ListCategoriesAsync(null);
        }
        
        /// <remarks/>
        public void ListCategoriesAsync(object userState) {
            if ((this.ListCategoriesOperationCompleted == null)) {
                this.ListCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListCategoriesOperationCompleted);
            }
            this.InvokeAsync("ListCategories", new object[0], this.ListCategoriesOperationCompleted, userState);
        }
        
        private void OnListCategoriesOperationCompleted(object arg) {
            if ((this.ListCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListCategoriesCompleted(this, new ListCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://service.boxberry.ru#Account:CheckAPI", RequestNamespace="http://service.boxberry.ru", ResponseNamespace="http://service.boxberry.ru", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", DataType="integer")]
        public string CheckAPI() {
            object[] results = this.Invoke("CheckAPI", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckAPIAsync() {
            this.CheckAPIAsync(null);
        }
        
        /// <remarks/>
        public void CheckAPIAsync(object userState) {
            if ((this.CheckAPIOperationCompleted == null)) {
                this.CheckAPIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckAPIOperationCompleted);
            }
            this.InvokeAsync("CheckAPI", new object[0], this.CheckAPIOperationCompleted, userState);
        }
        
        private void OnCheckAPIOperationCompleted(object arg) {
            if ((this.CheckAPICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckAPICompleted(this, new CheckAPICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Account")]
    public partial class Results {
        
        private string idField;
        
        private bool valueField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Account")]
    public partial class Categorie {
        
        private string nameField;
        
        private string kodField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Account")]
    public partial class ServicesBoxberry {
        
        private string serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RequisitesCompletedEventHandler(object sender, RequisitesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequisitesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequisitesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Results Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Results)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ServicesBoxberryCompletedEventHandler(object sender, ServicesBoxberryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServicesBoxberryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ServicesBoxberryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Results Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Results)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ListCategoriesCompletedEventHandler(object sender, ListCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Categorie[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Categorie[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CheckAPICompletedEventHandler(object sender, CheckAPICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckAPICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckAPICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591