//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WPSort.de.boxberry.mgrc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MgrcSoapBinding", Namespace="http://mgrc.boxberry.de")]
    public partial class MgrcSoap : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback parcelsFromTransportDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback parcelsScanResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback parcelInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback parcelMoveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MgrcSoap() {
            this.Url = global::WPSort.Properties.Settings.Default.WPSort_de_boxberry_mgrc_MgrcSoap;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event parcelsFromTransportDocumentCompletedEventHandler parcelsFromTransportDocumentCompleted;
        
        /// <remarks/>
        public event parcelsScanResultCompletedEventHandler parcelsScanResultCompleted;
        
        /// <remarks/>
        public event parcelInfoCompletedEventHandler parcelInfoCompleted;
        
        /// <remarks/>
        public event parcelMoveCompletedEventHandler parcelMoveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://mgrc.boxberry.de")]
        public parcelsFromTransportDocumentResult parcelsFromTransportDocument([System.Xml.Serialization.XmlElementAttribute(Namespace="http://mgrc.boxberry.de")] parcelsFromTransportDocumentRequest parcelsFromTransportDocumentRequest) {
            object[] results = this.Invoke("parcelsFromTransportDocument", new object[] {
                        parcelsFromTransportDocumentRequest});
            return ((parcelsFromTransportDocumentResult)(results[0]));
        }
        
        /// <remarks/>
        public void parcelsFromTransportDocumentAsync(parcelsFromTransportDocumentRequest parcelsFromTransportDocumentRequest) {
            this.parcelsFromTransportDocumentAsync(parcelsFromTransportDocumentRequest, null);
        }
        
        /// <remarks/>
        public void parcelsFromTransportDocumentAsync(parcelsFromTransportDocumentRequest parcelsFromTransportDocumentRequest, object userState) {
            if ((this.parcelsFromTransportDocumentOperationCompleted == null)) {
                this.parcelsFromTransportDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnparcelsFromTransportDocumentOperationCompleted);
            }
            this.InvokeAsync("parcelsFromTransportDocument", new object[] {
                        parcelsFromTransportDocumentRequest}, this.parcelsFromTransportDocumentOperationCompleted, userState);
        }
        
        private void OnparcelsFromTransportDocumentOperationCompleted(object arg) {
            if ((this.parcelsFromTransportDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.parcelsFromTransportDocumentCompleted(this, new parcelsFromTransportDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute(Namespace="http://mgrc.boxberry.de")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("parcels", IsNullable=false)]
        public parcelsScanedAnswer[] parcelsScanResult([System.Xml.Serialization.XmlElementAttribute(Namespace="http://mgrc.boxberry.de")] parcelsScanResultRequest parcelsScanResultRequest) {
            object[] results = this.Invoke("parcelsScanResult", new object[] {
                        parcelsScanResultRequest});
            return ((parcelsScanedAnswer[])(results[0]));
        }
        
        /// <remarks/>
        public void parcelsScanResultAsync(parcelsScanResultRequest parcelsScanResultRequest) {
            this.parcelsScanResultAsync(parcelsScanResultRequest, null);
        }
        
        /// <remarks/>
        public void parcelsScanResultAsync(parcelsScanResultRequest parcelsScanResultRequest, object userState) {
            if ((this.parcelsScanResultOperationCompleted == null)) {
                this.parcelsScanResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnparcelsScanResultOperationCompleted);
            }
            this.InvokeAsync("parcelsScanResult", new object[] {
                        parcelsScanResultRequest}, this.parcelsScanResultOperationCompleted, userState);
        }
        
        private void OnparcelsScanResultOperationCompleted(object arg) {
            if ((this.parcelsScanResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.parcelsScanResultCompleted(this, new parcelsScanResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute(Namespace="http://mgrc.boxberry.de")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("parcels", IsNullable=false)]
        public parcelInfoParcel[] parcelInfo([System.Xml.Serialization.XmlElementAttribute(Namespace="http://mgrc.boxberry.de")] parcelInfoRequest parcelInfoRequest) {
            object[] results = this.Invoke("parcelInfo", new object[] {
                        parcelInfoRequest});
            return ((parcelInfoParcel[])(results[0]));
        }
        
        /// <remarks/>
        public void parcelInfoAsync(parcelInfoRequest parcelInfoRequest) {
            this.parcelInfoAsync(parcelInfoRequest, null);
        }
        
        /// <remarks/>
        public void parcelInfoAsync(parcelInfoRequest parcelInfoRequest, object userState) {
            if ((this.parcelInfoOperationCompleted == null)) {
                this.parcelInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnparcelInfoOperationCompleted);
            }
            this.InvokeAsync("parcelInfo", new object[] {
                        parcelInfoRequest}, this.parcelInfoOperationCompleted, userState);
        }
        
        private void OnparcelInfoOperationCompleted(object arg) {
            if ((this.parcelInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.parcelInfoCompleted(this, new parcelInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://mgrc.boxberry.de")]
        public parcelMoveResult parcelMove([System.Xml.Serialization.XmlElementAttribute(Namespace="http://mgrc.boxberry.de")] parcelMoveRequest parcelMoveRequest) {
            object[] results = this.Invoke("parcelMove", new object[] {
                        parcelMoveRequest});
            return ((parcelMoveResult)(results[0]));
        }
        
        /// <remarks/>
        public void parcelMoveAsync(parcelMoveRequest parcelMoveRequest) {
            this.parcelMoveAsync(parcelMoveRequest, null);
        }
        
        /// <remarks/>
        public void parcelMoveAsync(parcelMoveRequest parcelMoveRequest, object userState) {
            if ((this.parcelMoveOperationCompleted == null)) {
                this.parcelMoveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnparcelMoveOperationCompleted);
            }
            this.InvokeAsync("parcelMove", new object[] {
                        parcelMoveRequest}, this.parcelMoveOperationCompleted, userState);
        }
        
        private void OnparcelMoveOperationCompleted(object arg) {
            if ((this.parcelMoveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.parcelMoveCompleted(this, new parcelMoveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mgrc.boxberry.de")]
    public partial class parcelsFromTransportDocumentRequest {
        
        private string tokenField;
        
        private string transportNumberField;
        
        private string fromField;
        
        private string limitStartField;
        
        private string limitCountField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string TransportNumber {
            get {
                return this.transportNumberField;
            }
            set {
                this.transportNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string limitStart {
            get {
                return this.limitStartField;
            }
            set {
                this.limitStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string limitCount {
            get {
                return this.limitCountField;
            }
            set {
                this.limitCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mgrc.boxberry.de")]
    public partial class parcelInfoMovement {
        
        private string idField;
        
        private string transportNumberField;
        
        private string fromField;
        
        private string toField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string TransportNumber {
            get {
                return this.transportNumberField;
            }
            set {
                this.transportNumberField = value;
            }
        }
        
        /// <remarks/>
        public string from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mgrc.boxberry.de")]
    public partial class parcelInfoParcel {
        
        private System.Nullable<bool> scanedField;
        
        private string barcodeField;
        
        private string client_nameField;
        
        private string countryField;
        
        private string country_сodeField;
        
        private string labelField;
        
        private string label_IDField;
        
        private parcelInfoMovement[] movementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Scaned {
            get {
                return this.scanedField;
            }
            set {
                this.scanedField = value;
            }
        }
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Client_name {
            get {
                return this.client_nameField;
            }
            set {
                this.client_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Country_сode {
            get {
                return this.country_сodeField;
            }
            set {
                this.country_сodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public string Label_ID {
            get {
                return this.label_IDField;
            }
            set {
                this.label_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("movement")]
        public parcelInfoMovement[] movement {
            get {
                return this.movementField;
            }
            set {
                this.movementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mgrc.boxberry.de")]
    public partial class parcelsScanedAnswer {
        
        private string label_IDField;
        
        private string errorField;
        
        /// <remarks/>
        public string Label_ID {
            get {
                return this.label_IDField;
            }
            set {
                this.label_IDField = value;
            }
        }
        
        /// <remarks/>
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mgrc.boxberry.de")]
    public partial class parcelsScaned {
        
        private string label_IDField;
        
        private string boxField;
        
        private string palletField;
        
        /// <remarks/>
        public string Label_ID {
            get {
                return this.label_IDField;
            }
            set {
                this.label_IDField = value;
            }
        }
        
        /// <remarks/>
        public string box {
            get {
                return this.boxField;
            }
            set {
                this.boxField = value;
            }
        }
        
        /// <remarks/>
        public string pallet {
            get {
                return this.palletField;
            }
            set {
                this.palletField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mgrc.boxberry.de")]
    public partial class parcelsData {
        
        private System.Nullable<bool> scanedField;
        
        private string barcodeField;
        
        private string client_nameField;
        
        private string countryField;
        
        private string country_сodeField;
        
        private string labelField;
        
        private string label_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Scaned {
            get {
                return this.scanedField;
            }
            set {
                this.scanedField = value;
            }
        }
        
        /// <remarks/>
        public string Barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Client_name {
            get {
                return this.client_nameField;
            }
            set {
                this.client_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Country_сode {
            get {
                return this.country_сodeField;
            }
            set {
                this.country_сodeField = value;
            }
        }
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public string Label_ID {
            get {
                return this.label_IDField;
            }
            set {
                this.label_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mgrc.boxberry.de")]
    public partial class parcelsFromTransportDocumentResult {
        
        private string idField;
        
        private string transportNumberField;
        
        private string fromField;
        
        private string toField;
        
        private string totalField;
        
        private string limitStartField;
        
        private string limitEndField;
        
        private parcelsData[] parcelsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string TransportNumber {
            get {
                return this.transportNumberField;
            }
            set {
                this.transportNumberField = value;
            }
        }
        
        /// <remarks/>
        public string from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string limitStart {
            get {
                return this.limitStartField;
            }
            set {
                this.limitStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string limitEnd {
            get {
                return this.limitEndField;
            }
            set {
                this.limitEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parcels")]
        public parcelsData[] parcels {
            get {
                return this.parcelsField;
            }
            set {
                this.parcelsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mgrc.boxberry.de")]
    public partial class parcelsScanResultRequest {
        
        private string tokenField;
        
        private parcelsScaned[] parcelsField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parcels")]
        public parcelsScaned[] parcels {
            get {
                return this.parcelsField;
            }
            set {
                this.parcelsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mgrc.boxberry.de")]
    public partial class parcelInfoRequest {
        
        private string tokenField;
        
        private string label_IDField;
        
        private System.Nullable<bool> labelField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string Label_ID {
            get {
                return this.label_IDField;
            }
            set {
                this.label_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mgrc.boxberry.de")]
    public partial class parcelMoveRequest {
        
        private string tokenField;
        
        private string label_IDField;
        
        private string move_TOField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string Label_ID {
            get {
                return this.label_IDField;
            }
            set {
                this.label_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Move_TO {
            get {
                return this.move_TOField;
            }
            set {
                this.move_TOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://mgrc.boxberry.de")]
    public partial class parcelMoveResult {
        
        private string errorField;
        
        private string error_textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string error_text {
            get {
                return this.error_textField;
            }
            set {
                this.error_textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void parcelsFromTransportDocumentCompletedEventHandler(object sender, parcelsFromTransportDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class parcelsFromTransportDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal parcelsFromTransportDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public parcelsFromTransportDocumentResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((parcelsFromTransportDocumentResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void parcelsScanResultCompletedEventHandler(object sender, parcelsScanResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class parcelsScanResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal parcelsScanResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public parcelsScanedAnswer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((parcelsScanedAnswer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void parcelInfoCompletedEventHandler(object sender, parcelInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class parcelInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal parcelInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public parcelInfoParcel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((parcelInfoParcel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void parcelMoveCompletedEventHandler(object sender, parcelMoveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class parcelMoveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal parcelMoveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public parcelMoveResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((parcelMoveResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591